name: Framework CLI Tests
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-framework-cli
  cancel-in-progress: true
jobs:
  framework-component-tests:
    defaults:
      run:
        working-directory: framework/cmd
    env:
      CTF_JD_IMAGE: ${{ secrets.CTF_JD_IMAGE }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          role-to-assume: ${{ secrets.PUBLIC_AWS_ECR_ROLE }}
          aws-region: us-east-1
      - name: Authenticate to ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registry-type: public
      - name: Check for changes in Framework
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            src:
              - 'framework/cmd/**'
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.0'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-modules-${{ hashFiles('**/go.sum') }}-${{ runner.os }}-framework
          restore-keys: |
            go-modules-${{ hashFiles('**/go.sum') }}-${{ runner.os }}-framework
      - name: Install dependencies
        run: go mod download
      - name: Run Docker Component Tests
        if: steps.changes.outputs.src == 'true'
        run: |
          go test -race -timeout 2m -v -count 1 -run TestCLI
