name: Module graph
on:
  pull_request:
jobs:
  modgraph:
    runs-on: ubuntu-latest
    name: modgraph
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Setup Go
        uses: actions/setup-go@v6
      - run: make modgraph
      - name: Ensure clean modgraph
        run: git diff --minimal --exit-code
